language: python
dist: xenial
python: 3.7
before_install:
  - sudo apt-get update
  - sudo apt-get install -y hunspell hunspell-hi
install:
  - pip install pospell "powrap>=0.3.0"
  - pospell --version
  - powrap --version
script:
  - powrap --check --quiet **/*.po
  - pospell -p dict -l hi_IN **/*.po
- make CPYTHON_CLONE=/tmp/cpython/ COMMIT=905ce9eeb1d1f4e8a1e914c3ec61767490d40ec6
